name       : antimicrox
version    : 3.1.7
release    : 8
source     :
    - https://github.com/AntiMicroX/antimicrox/archive/refs/tags/3.1.7.tar.gz : 6ba9788eb1c212a9b7345e75db8dfc7b6b8cd3f5d14b285c976ae7edb2d9eae6
homepage   : https://github.com/AntiMicroX/antimicrox
license    : GPL-3.0-or-later
component  : games
summary    : antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad
description: |
    antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - itstool
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/antimicrox/CHANGELOG.md

