name       : antimicrox
version    : 3.1.6
release    : 7
source     :
    - https://github.com/AntiMicroX/antimicrox/archive/3.1.6.tar.gz : 3437d32764e57e10d8fbaaec4e7d57bef626f89f67f876002648fab45cb15053
homepage   : https://github.com/AntiMicroX/antimicrox
license    : GPL-3.0-or-later
component  : games
summary    : antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad
description: |
    antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - itstool
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/antimicrox/CHANGELOG.md

