name        : antimicrox
version     : 2.25.0
release     : 1
source      :
    - https://github.com/juliagoda/antimicroX/archive/2.25.tar.gz : 349a980addac44414f9e4c5d1f4c58fc15ac48c639cc07c2f3bfb416c79f94fe
homepage    : https://github.com/juliagoda/antimicroX
license     : GPL-3.0-or-later
component   : games
summary     : antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad
description : |
    antimicro is a graphical program used to map keyboard keys and mouse controls to a gamepad
builddeps   :
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - itstool
libsplit    : no
setup       : |
    %cmake
build       : |
    %make
install     : |
    %make_install
